name: image_craft
description: ImageCraft aims to simplify image handling in Flutter applications while providing robust caching mechanisms.
version: 1.0.2
homepage: https://github.com/dev-mahmoud-elshenawy/image_craft
repository: https://github.com/dev-mahmoud-elshenawy/image_craft
issue_tracker: https://github.com/dev-mahmoud-elshenawy/image_craft/issues
license: MIT

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path: ^1.9.0
  path_provider: ^2.1.4
  http: ^1.2.2
  flutter_svg: ^2.0.10+1
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/